const ProjectsList = [
  {
    id: 0,
    title: 'PageProbe',
    description:
      'PageProbe is a .NET 8-based open-source web crawler library for C# that enables automated retrieval and monitoring of content from statically generated websites.',
    details:
      'PageProbe is a simple and extensible .NET 8 library for web crawling and content extraction. It supports HTML parsing, handling of robots.txt, and can extract data such as text, metadata, images, links, and multimedia. Results can be exported to CSV, JSON, XML, or Markdown. The library is designed to be testable and easy to extend, making it suitable for automation, data mining, and content monitoring on websites without APIs.',
    localPath: 'pageprobe',
    url: 'https://github.com/EmilB04/Rammeverk-og-.NET/tree/main/Project/PageProbe',
    tags: [
      '.NET',
      'dotnet8',
      'C#',
      'open-source',
      'web-crawler',
      'site-crawler',
      'html-parsing',
      'robots.txt',
      'data-extraction',
      'content-extraction',
      'csv',
      'json',
      'xml',
      'markdown',
      'text',
      'metadata',
      'images',
      'links',
      'multimedia',
      'extensible',
      'testable',
      'automation',
      'data-mining',
      'library',
    ],
  },
  {
    id: 1,
    title: 'VarsEL',
    description:
      'VarsEL is an open-source project that offers a simple and efficient way to view and retrieve electricity prices in Norway.',
    details:
      'VarsEL is a Java library with Vue and Quasar front-end that provides access to electricity prices in Norway. It fetches data from hvakosterstrømmen.no and offers a simple API for retrieving electricity prices for different time periods. The project is designed to be easy to use and integrate into other applications, supporting both real-time data and historical prices.',
    localPath: 'varsel',
    url: 'https://github.com/EmilB04/VarsEL',
    tags: [
      'Java',
      'Vue',
      'Quasar',
      'npm',
      'open-source',
      'electricity-prices',
      'Norway',
      'API',
      'real-time-data',
      'historical-prices',
      'hvakosterstrømmen.no',
      'data-access',
      'library',
      'integration',
    ],
  },
];

export default ProjectsList;
